server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ays?rewriteBatchedStatements=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  环境设置：dev、test、prod
  profiles:
    active: dev
#最大上传单个文件大小：默认1M
  servlet:
    multipart:
      max-file-size: 1024MB
# 最大总上传的数据大小 ：默认10M
      max-request-size: 1024MB


  redis:
    host: 192.168.126.151
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
#最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        max-idle: 5
        min-idle: 0


#阿里云 OSS
#阿里云视频点播 vod
aliyun:
  oss:
    file:
      endPoint: oss-cn-beijing.aliyuncs.com
      keyId: LTAI5tCDtJWscz3yCHmAuSLp
      keySecret: LPNSZUYXxRFpxCvXxwoxeNea8CP2K9
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketName: ays-pic
  vod:
    file:
      keyId: LTAI5tCDtJWscz3yCHmAuSLp
      keySecret: LPNSZUYXxRFpxCvXxwoxeNea8CP2K9





#mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #mybatis日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mapper存放位置
  mapper-locations: classpath:com/marvin/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted

#设置整个项目日志级别
#logging:
#  level:
#    root: info
